spring:
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix:
#    encoding: UTF-8
#    mode: HTML5
#    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/library3?serverTimezone=UTC
    username: root
    password: wan
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html

mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hfnu.library.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


server:
  port: 8081

